name: Feature request
description: Propose a change.
title: "[feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is missing?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed change
    validations:
      required: true
